project:
  type: website
  output-dir: _site

website:
  title: "Chia-Chen Hsu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Project
      - href: cv.qmd
        text: Curriculum Vitae
      

format:
  html:
    theme: cosmo
    toc: false
